name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Run tests
        run: go test ./...

      - name: Run Go vet
        run: go vet ./...

      - name: Check Go formatting
        run: test -z "$(gofmt -l .)"

      - name: Run Go lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
